
version: '3.1'
services:
    openrum:
      build: .
      volumes:
        - ./:/home/node/app
      # command: npm run build:dev
      ports:
        - 5000:5000
      networks:
        - web
    mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      ports:
        - 27017:27017
      volumes:
        - "mongo-data:/data/db"
      networks:
        - web
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
      networks:
        - web
volumes:
  mongo-data:

networks:
  web:
